export interface Country {
  code: string;
  alpha3: string;
  nameEs: string;
  nameEn: string;
}

export const COUNTRIES: Country[] = [
  { code: 'AF', alpha3: 'AFG', nameEs: 'Afganistán', nameEn: 'Afganistán' },
  { code: 'AL', alpha3: 'ALB', nameEs: 'Albania', nameEn: 'Albania' },
  { code: 'DE', alpha3: 'DEU', nameEs: 'Alemania', nameEn: 'Alemania' },
  { code: 'AD', alpha3: 'AND', nameEs: 'Andorra', nameEn: 'Andorra' },
  { code: 'AO', alpha3: 'AGO', nameEs: 'Angola', nameEn: 'Angola' },
  { code: 'AI', alpha3: 'AIA', nameEs: 'Anguila', nameEn: 'Anguila' },
  { code: 'AQ', alpha3: 'ATA', nameEs: 'Antártida', nameEn: 'Antártida' },
  { code: 'AG', alpha3: 'ATG', nameEs: 'Antigua y Barbuda', nameEn: 'Antigua y Barbuda' },
  { code: 'SA', alpha3: 'SAU', nameEs: 'Arabia Saudita', nameEn: 'Arabia Saudita' },
  { code: 'DZ', alpha3: 'DZA', nameEs: 'Argelia', nameEn: 'Argelia' },
  { code: 'AR', alpha3: 'ARG', nameEs: 'Argentina', nameEn: 'Argentina' },
  { code: 'AM', alpha3: 'ARM', nameEs: 'Armenia', nameEn: 'Armenia' },
  { code: 'AW', alpha3: 'ABW', nameEs: 'Aruba', nameEn: 'Aruba' },
  { code: 'AU', alpha3: 'AUS', nameEs: 'Australia', nameEn: 'Australia' },
  { code: 'AT', alpha3: 'AUT', nameEs: 'Austria', nameEn: 'Austria' },
  { code: 'AZ', alpha3: 'AZE', nameEs: 'Azerbaiyán', nameEn: 'Azerbaiyán' },
  { code: 'BS', alpha3: 'BHS', nameEs: 'Bahamas', nameEn: 'Bahamas' },
  { code: 'BD', alpha3: 'BGD', nameEs: 'Bangladés', nameEn: 'Bangladés' },
  { code: 'BB', alpha3: 'BRB', nameEs: 'Barbados', nameEn: 'Barbados' },
  { code: 'BH', alpha3: 'BHR', nameEs: 'Baréin', nameEn: 'Baréin' },
  { code: 'BE', alpha3: 'BEL', nameEs: 'Bélgica', nameEn: 'Bélgica' },
  { code: 'BZ', alpha3: 'BLZ', nameEs: 'Belice', nameEn: 'Belice' },
  { code: 'BJ', alpha3: 'BEN', nameEs: 'Benín', nameEn: 'Benín' },
  { code: 'BM', alpha3: 'BMU', nameEs: 'Bermudas', nameEn: 'Bermudas' },
  { code: 'BY', alpha3: 'BLR', nameEs: 'Bielorrusia', nameEn: 'Bielorrusia' },
  { code: 'MM', alpha3: 'MMR', nameEs: 'Birmania', nameEn: 'Birmania' },
  { code: 'BO', alpha3: 'BOL', nameEs: 'Bolivia', nameEn: 'Bolivia' },
  { code: 'BA', alpha3: 'BIH', nameEs: 'Bosnia y Herzegovina', nameEn: 'Bosnia y Herzegovina' },
  { code: 'BW', alpha3: 'BWA', nameEs: 'Botsuana', nameEn: 'Botsuana' },
  { code: 'BR', alpha3: 'BRA', nameEs: 'Brasil', nameEn: 'Brasil' },
  { code: 'BN', alpha3: 'BRN', nameEs: 'Brunéi', nameEn: 'Brunéi' },
  { code: 'BG', alpha3: 'BGR', nameEs: 'Bulgaria', nameEn: 'Bulgaria' },
  { code: 'BF', alpha3: 'BFA', nameEs: 'Burkina Faso', nameEn: 'Burkina Faso' },
  { code: 'BI', alpha3: 'BDI', nameEs: 'Burundi', nameEn: 'Burundi' },
  { code: 'BT', alpha3: 'BTN', nameEs: 'Bután', nameEn: 'Bután' },
  { code: 'CV', alpha3: 'CPV', nameEs: 'Cabo Verde', nameEn: 'Cabo Verde' },
  { code: 'KH', alpha3: 'KHM', nameEs: 'Camboya', nameEn: 'Camboya' },
  { code: 'CM', alpha3: 'CMR', nameEs: 'Camerún', nameEn: 'Camerún' },
  { code: 'CA', alpha3: 'CAN', nameEs: 'Canadá', nameEn: 'Canadá' },
  { code: 'QA', alpha3: 'QAT', nameEs: 'Catar', nameEn: 'Catar' },
  { code: 'TD', alpha3: 'TCD', nameEs: 'Chad', nameEn: 'Chad' },
  { code: 'CL', alpha3: 'CHL', nameEs: 'Chile', nameEn: 'Chile' },
  { code: 'CN', alpha3: 'CHN', nameEs: 'China', nameEn: 'China' },
  { code: 'CY', alpha3: 'CYP', nameEs: 'Chipre', nameEn: 'Chipre' },
  { code: 'CO', alpha3: 'COL', nameEs: 'Colombia', nameEn: 'Colombia' },
  { code: 'KM', alpha3: 'COM', nameEs: 'Comoras', nameEn: 'Comoras' },
  { code: 'CG', alpha3: 'COG', nameEs: 'Congo', nameEn: 'Congo' },
  { code: 'KP', alpha3: 'PRK', nameEs: 'Corea del Norte', nameEn: 'Corea del Norte' },
  { code: 'KR', alpha3: 'KOR', nameEs: 'Corea del Sur', nameEn: 'Corea del Sur' },
  { code: 'CR', alpha3: 'CRI', nameEs: 'Costa Rica', nameEn: 'Costa Rica' },
  { code: 'CI', alpha3: 'CIV', nameEs: 'Costa de Marfil', nameEn: 'Costa de Marfil' },
  { code: 'HR', alpha3: 'HRV', nameEs: 'Croacia', nameEn: 'Croacia' },
  { code: 'CU', alpha3: 'CUB', nameEs: 'Cuba', nameEn: 'Cuba' },
  { code: 'CW', alpha3: 'CUW', nameEs: 'Curazao', nameEn: 'Curazao' },
  { code: 'DK', alpha3: 'DNK', nameEs: 'Dinamarca', nameEn: 'Dinamarca' },
  { code: 'DM', alpha3: 'DMA', nameEs: 'Dominica', nameEn: 'Dominica' },
  { code: 'EC', alpha3: 'ECU', nameEs: 'Ecuador', nameEn: 'Ecuador' },
  { code: 'EG', alpha3: 'EGY', nameEs: 'Egipto', nameEn: 'Egipto' },
  { code: 'SV', alpha3: 'SLV', nameEs: 'El Salvador', nameEn: 'El Salvador' },
  { code: 'AE', alpha3: 'ARE', nameEs: 'Emiratos Árabes Unidos', nameEn: 'Emiratos Árabes Unidos' },
  { code: 'ER', alpha3: 'ERI', nameEs: 'Eritrea', nameEn: 'Eritrea' },
  { code: 'SK', alpha3: 'SVK', nameEs: 'Eslovaquia', nameEn: 'Eslovaquia' },
  { code: 'SI', alpha3: 'SVN', nameEs: 'Eslovenia', nameEn: 'Eslovenia' },
  { code: 'ES', alpha3: 'ESP', nameEs: 'España', nameEn: 'España' },
  { code: 'US', alpha3: 'USA', nameEs: 'Estados Unidos', nameEn: 'Estados Unidos' },
  { code: 'EE', alpha3: 'EST', nameEs: 'Estonia', nameEn: 'Estonia' },
  { code: 'SZ', alpha3: 'SWZ', nameEs: 'Esuatini', nameEn: 'Esuatini' },
  { code: 'ET', alpha3: 'ETH', nameEs: 'Etiopía', nameEn: 'Etiopía' },
  { code: 'PH', alpha3: 'PHL', nameEs: 'Filipinas', nameEn: 'Filipinas' },
  { code: 'FI', alpha3: 'FIN', nameEs: 'Finlandia', nameEn: 'Finlandia' },
  { code: 'FJ', alpha3: 'FJI', nameEs: 'Fiyi', nameEn: 'Fiyi' },
  { code: 'FR', alpha3: 'FRA', nameEs: 'Francia', nameEn: 'Francia' },
  { code: 'GA', alpha3: 'GAB', nameEs: 'Gabón', nameEn: 'Gabón' },
  { code: 'GM', alpha3: 'GMB', nameEs: 'Gambia', nameEn: 'Gambia' },
  { code: 'GE', alpha3: 'GEO', nameEs: 'Georgia', nameEn: 'Georgia' },
  { code: 'GH', alpha3: 'GHA', nameEs: 'Ghana', nameEn: 'Ghana' },
  { code: 'GI', alpha3: 'GIB', nameEs: 'Gibraltar', nameEn: 'Gibraltar' },
  { code: 'GD', alpha3: 'GRD', nameEs: 'Granada', nameEn: 'Granada' },
  { code: 'GR', alpha3: 'GRC', nameEs: 'Grecia', nameEn: 'Grecia' },
  { code: 'GL', alpha3: 'GRL', nameEs: 'Groenlandia', nameEn: 'Groenlandia' },
  { code: 'GT', alpha3: 'GTM', nameEs: 'Guatemala', nameEn: 'Guatemala' },
  { code: 'GF', alpha3: 'GUF', nameEs: 'Guayana Francesa', nameEn: 'Guayana Francesa' },
  { code: 'GN', alpha3: 'GIN', nameEs: 'Guinea', nameEn: 'Guinea' },
  { code: 'GQ', alpha3: 'GNQ', nameEs: 'Guinea Ecuatorial', nameEn: 'Guinea Ecuatorial' },
  { code: 'GW', alpha3: 'GNB', nameEs: 'Guinea-Bisáu', nameEn: 'Guinea-Bisáu' },
  { code: 'GY', alpha3: 'GUY', nameEs: 'Guyana', nameEn: 'Guyana' },
  { code: 'HT', alpha3: 'HTI', nameEs: 'Haití', nameEn: 'Haití' },
  { code: 'HN', alpha3: 'HND', nameEs: 'Honduras', nameEn: 'Honduras' },
  { code: 'HU', alpha3: 'HUN', nameEs: 'Hungría', nameEn: 'Hungría' },
  { code: 'IN', alpha3: 'IND', nameEs: 'India', nameEn: 'India' },
  { code: 'ID', alpha3: 'IDN', nameEs: 'Indonesia', nameEn: 'Indonesia' },
  { code: 'IQ', alpha3: 'IRQ', nameEs: 'Irak', nameEn: 'Irak' },
  { code: 'IR', alpha3: 'IRN', nameEs: 'Irán', nameEn: 'Irán' },
  { code: 'IE', alpha3: 'IRL', nameEs: 'Irlanda', nameEn: 'Irlanda' },
  { code: 'IS', alpha3: 'ISL', nameEs: 'Islandia', nameEn: 'Islandia' },
  { code: 'IL', alpha3: 'ISR', nameEs: 'Israel', nameEn: 'Israel' },
  { code: 'IT', alpha3: 'ITA', nameEs: 'Italia', nameEn: 'Italia' },
  { code: 'JM', alpha3: 'JAM', nameEs: 'Jamaica', nameEn: 'Jamaica' },
  { code: 'JP', alpha3: 'JPN', nameEs: 'Japón', nameEn: 'Japón' },
  { code: 'JO', alpha3: 'JOR', nameEs: 'Jordania', nameEn: 'Jordania' },
  { code: 'KZ', alpha3: 'KAZ', nameEs: 'Kazajistán', nameEn: 'Kazajistán' },
  { code: 'KE', alpha3: 'KEN', nameEs: 'Kenia', nameEn: 'Kenia' },
  { code: 'KG', alpha3: 'KGZ', nameEs: 'Kirguistán', nameEn: 'Kirguistán' },
  { code: 'KI', alpha3: 'KIR', nameEs: 'Kiribati', nameEn: 'Kiribati' },
  { code: 'KW', alpha3: 'KWT', nameEs: 'Kuwait', nameEn: 'Kuwait' },
  { code: 'LA', alpha3: 'LAO', nameEs: 'Laos', nameEn: 'Laos' },
  { code: 'LS', alpha3: 'LSO', nameEs: 'Lesoto', nameEn: 'Lesoto' },
  { code: 'LV', alpha3: 'LVA', nameEs: 'Letonia', nameEn: 'Letonia' },
  { code: 'LB', alpha3: 'LBN', nameEs: 'Líbano', nameEn: 'Líbano' },
  { code: 'LR', alpha3: 'LBR', nameEs: 'Liberia', nameEn: 'Liberia' },
  { code: 'LY', alpha3: 'LBY', nameEs: 'Libia', nameEn: 'Libia' },
  { code: 'LI', alpha3: 'LIE', nameEs: 'Liechtenstein', nameEn: 'Liechtenstein' },
  { code: 'LT', alpha3: 'LTU', nameEs: 'Lituania', nameEn: 'Lituania' },
  { code: 'LU', alpha3: 'LUX', nameEs: 'Luxemburgo', nameEn: 'Luxemburgo' },
  { code: 'MK', alpha3: 'MKD', nameEs: 'Macedonia del Norte', nameEn: 'Macedonia del Norte' },
  { code: 'MG', alpha3: 'MDG', nameEs: 'Madagascar', nameEn: 'Madagascar' },
  { code: 'MY', alpha3: 'MYS', nameEs: 'Malasia', nameEn: 'Malasia' },
  { code: 'MW', alpha3: 'MWI', nameEs: 'Malaui', nameEn: 'Malaui' },
  { code: 'MV', alpha3: 'MDV', nameEs: 'Maldivas', nameEn: 'Maldivas' },
  { code: 'ML', alpha3: 'MLI', nameEs: 'Malí', nameEn: 'Malí' },
  { code: 'MT', alpha3: 'MLT', nameEs: 'Malta', nameEn: 'Malta' },
  { code: 'MA', alpha3: 'MAR', nameEs: 'Marruecos', nameEn: 'Marruecos' },
  { code: 'MU', alpha3: 'MUS', nameEs: 'Mauricio', nameEn: 'Mauricio' },
  { code: 'MR', alpha3: 'MRT', nameEs: 'Mauritania', nameEn: 'Mauritania' },
  { code: 'MX', alpha3: 'MEX', nameEs: 'México', nameEn: 'México' },
  { code: 'FM', alpha3: 'FSM', nameEs: 'Micronesia', nameEn: 'Micronesia' },
  { code: 'MD', alpha3: 'MDA', nameEs: 'Moldavia', nameEn: 'Moldavia' },
  { code: 'MC', alpha3: 'MCO', nameEs: 'Mónaco', nameEn: 'Mónaco' },
  { code: 'MN', alpha3: 'MNG', nameEs: 'Mongolia', nameEn: 'Mongolia' },
  { code: 'ME', alpha3: 'MNE', nameEs: 'Montenegro', nameEn: 'Montenegro' },
  { code: 'MZ', alpha3: 'MOZ', nameEs: 'Mozambique', nameEn: 'Mozambique' },
  { code: 'NA', alpha3: 'NAM', nameEs: 'Namibia', nameEn: 'Namibia' },
  { code: 'NR', alpha3: 'NRU', nameEs: 'Nauru', nameEn: 'Nauru' },
  { code: 'NP', alpha3: 'NPL', nameEs: 'Nepal', nameEn: 'Nepal' },
  { code: 'NI', alpha3: 'NIC', nameEs: 'Nicaragua', nameEn: 'Nicaragua' },
  { code: 'NE', alpha3: 'NER', nameEs: 'Níger', nameEn: 'Níger' },
  { code: 'NG', alpha3: 'NGA', nameEs: 'Nigeria', nameEn: 'Nigeria' },
  { code: 'NO', alpha3: 'NOR', nameEs: 'Noruega', nameEn: 'Noruega' },
  { code: 'NZ', alpha3: 'NZL', nameEs: 'Nueva Zelanda', nameEn: 'Nueva Zelanda' },
  { code: 'OM', alpha3: 'OMN', nameEs: 'Omán', nameEn: 'Omán' },
  { code: 'NL', alpha3: 'NLD', nameEs: 'Países Bajos', nameEn: 'Países Bajos' },
  { code: 'PK', alpha3: 'PAK', nameEs: 'Pakistán', nameEn: 'Pakistán' },
  { code: 'PW', alpha3: 'PLW', nameEs: 'Palaos', nameEn: 'Palaos' },
  { code: 'PA', alpha3: 'PAN', nameEs: 'Panamá', nameEn: 'Panamá' },
  { code: 'PG', alpha3: 'PNG', nameEs: 'Papúa Nueva Guinea', nameEn: 'Papúa Nueva Guinea' },
  { code: 'PY', alpha3: 'PRY', nameEs: 'Paraguay', nameEn: 'Paraguay' },
  { code: 'PE', alpha3: 'PER', nameEs: 'Perú', nameEn: 'Perú' },
  { code: 'PL', alpha3: 'POL', nameEs: 'Polonia', nameEn: 'Polonia' },
  { code: 'PT', alpha3: 'PRT', nameEs: 'Portugal', nameEn: 'Portugal' },
  { code: 'PR', alpha3: 'PRI', nameEs: 'Puerto Rico', nameEn: 'Puerto Rico' },
  { code: 'UK', alpha3: 'GBR', nameEs: 'Reino Unido', nameEn: 'Reino Unido' },
  { code: 'GB', alpha3: 'GBR', nameEs: 'Reino Unido', nameEn: 'Reino Unido' },
  { code: 'CF', alpha3: 'CAF', nameEs: 'República Centroafricana', nameEn: 'República Centroafricana' },
  { code: 'CZ', alpha3: 'CZE', nameEs: 'República Checa', nameEn: 'República Checa' },
  { code: 'DO', alpha3: 'DOM', nameEs: 'República Dominicana', nameEn: 'República Dominicana' },
  { code: 'RW', alpha3: 'RWA', nameEs: 'Ruanda', nameEn: 'Ruanda' },
  { code: 'RO', alpha3: 'ROU', nameEs: 'Rumanía', nameEn: 'Rumanía' },
  { code: 'RU', alpha3: 'RUS', nameEs: 'Rusia', nameEn: 'Rusia' },
  { code: 'WS', alpha3: 'WSM', nameEs: 'Samoa', nameEn: 'Samoa' },
  { code: 'SM', alpha3: 'SMR', nameEs: 'San Marino', nameEn: 'San Marino' },
  { code: 'SN', alpha3: 'SEN', nameEs: 'Senegal', nameEn: 'Senegal' },
  { code: 'RS', alpha3: 'SRB', nameEs: 'Serbia', nameEn: 'Serbia' },
  { code: 'SC', alpha3: 'SYC', nameEs: 'Seychelles', nameEn: 'Seychelles' },
  { code: 'SG', alpha3: 'SGP', nameEs: 'Singapur', nameEn: 'Singapur' },
  { code: 'SY', alpha3: 'SYR', nameEs: 'Siria', nameEn: 'Siria' },
  { code: 'SO', alpha3: 'SOM', nameEs: 'Somalia', nameEn: 'Somalia' },
  { code: 'LK', alpha3: 'LKA', nameEs: 'Sri Lanka', nameEn: 'Sri Lanka' },
  { code: 'ZA', alpha3: 'ZAF', nameEs: 'Sudáfrica', nameEn: 'Sudáfrica' },
  { code: 'SD', alpha3: 'SDN', nameEs: 'Sudán', nameEn: 'Sudán' },
  { code: 'SS', alpha3: 'SSD', nameEs: 'Sudán del Sur', nameEn: 'Sudán del Sur' },
  { code: 'SE', alpha3: 'SWE', nameEs: 'Suecia', nameEn: 'Suecia' },
  { code: 'CH', alpha3: 'CHE', nameEs: 'Suiza', nameEn: 'Suiza' },
  { code: 'SR', alpha3: 'SUR', nameEs: 'Surinam', nameEn: 'Surinam' },
  { code: 'TH', alpha3: 'THA', nameEs: 'Tailandia', nameEn: 'Tailandia' },
  { code: 'TW', alpha3: 'TWN', nameEs: 'Taiwán', nameEn: 'Taiwán' },
  { code: 'TZ', alpha3: 'TZA', nameEs: 'Tanzania', nameEn: 'Tanzania' },
  { code: 'TJ', alpha3: 'TJK', nameEs: 'Tayikistán', nameEn: 'Tayikistán' },
  { code: 'TL', alpha3: 'TLS', nameEs: 'Timor Oriental', nameEn: 'Timor Oriental' },
  { code: 'TG', alpha3: 'TGO', nameEs: 'Togo', nameEn: 'Togo' },
  { code: 'TO', alpha3: 'TON', nameEs: 'Tonga', nameEn: 'Tonga' },
  { code: 'TT', alpha3: 'TTO', nameEs: 'Trinidad y Tobago', nameEn: 'Trinidad y Tobago' },
  { code: 'TN', alpha3: 'TUN', nameEs: 'Túnez', nameEn: 'Túnez' },
  { code: 'TM', alpha3: 'TKM', nameEs: 'Turkmenistán', nameEn: 'Turkmenistán' },
  { code: 'TR', alpha3: 'TUR', nameEs: 'Turquía', nameEn: 'Turquía' },
  { code: 'TV', alpha3: 'TUV', nameEs: 'Tuvalu', nameEn: 'Tuvalu' },
  { code: 'UA', alpha3: 'UKR', nameEs: 'Ucrania', nameEn: 'Ucrania' },
  { code: 'UG', alpha3: 'UGA', nameEs: 'Uganda', nameEn: 'Uganda' },
  { code: 'UY', alpha3: 'URY', nameEs: 'Uruguay', nameEn: 'Uruguay' },
  { code: 'UZ', alpha3: 'UZB', nameEs: 'Uzbekistán', nameEn: 'Uzbekistán' },
  { code: 'VU', alpha3: 'VUT', nameEs: 'Vanuatu', nameEn: 'Vanuatu' },
  { code: 'VE', alpha3: 'VEN', nameEs: 'Venezuela', nameEn: 'Venezuela' },
  { code: 'VN', alpha3: 'VNM', nameEs: 'Vietnam', nameEn: 'Vietnam' },
  { code: 'YE', alpha3: 'YEM', nameEs: 'Yemen', nameEn: 'Yemen' },
  { code: 'DJ', alpha3: 'DJI', nameEs: 'Yibuti', nameEn: 'Yibuti' },
  { code: 'ZM', alpha3: 'ZMB', nameEs: 'Zambia', nameEn: 'Zambia' },
  { code: 'ZW', alpha3: 'ZWE', nameEs: 'Zimbabue', nameEn: 'Zimbabue' }
];

// Helper to quickly find alpha3 by code
export function getAlpha3FromCode(code: string): string {
  const c = COUNTRIES.find((c) => c.code === code.toUpperCase());
  return c ? c.alpha3 : '';
}
